### ISSUE TITLE
Portability?

### ISSUE THREAD

**Issue by narcolepticinsomniac** [henrypp/chromium#25] opened 2017-06-15 19:34 UTC
Has something changed? I know Google Chrome has always imposed arbitrary restrictions, which locked most profile settings to the computer they're installed on, but Chromium portable installs were always fully transportable for me, up until recently. 

This has always been a major convenience, but lately, attempting to copy and transfer the portable install to another computer isn't working.  It's behaving like Chrome, and all extensions aren't transferring. This is a major PITA. Has Chromium started locking profile settings, or am I doing something wrong?

stable-codecs-sync

**Comment by uBlock-user** [comment] 2017-06-16 14:01
Are you using the archive build  or the portable build downloaded via chrlauncher ?

**Comment by narcolepticinsomniac** [comment] 2017-06-16 19:04
chrlauncher. Builds downloaded via chrlauncher were always truly portable in the past, so I didn't think it was the problem. I did update chrlauncher somewhat recently, but I'm not sure if that coincides with this portability issue. I typically do a full transfer every 2-3 months from my primary laptop to my "entertainment center" desktop. These transfers always worked, but started failing at least a few months back.

**Comment by uBlock-user** [comment] 2017-06-17 08:16
Started failing as in you cannot copy/paste ?

**Comment by chrme** [comment] 2017-06-17 12:32
i don't know about this problem, but chrlauncher and my build config is the same like always, the one thing that always change is chromium base

**Comment by niutech** [comment] 2017-06-18 01:20
I have the same issue - when I install some extension in the portable version of your Chromium build using Chrlauncher, and when I copy the whole folder to another computer, the extensions aren't working (none of them are listed in `chrome://extensions`).

**Comment by narcolepticinsomniac** [comment] 2017-06-18 02:50
Yeah, copying the whole portable folder and pasting to another computer isn't working anymore. Chrome has always been like that, even in "portable" installs, but Chromium portables downloaded via chrlauncher always worked. Stopped working around v56, which was also around the same time I updated chrlauncher. Not sure if Chromium itself is screwed now, or if chrlauncher has anything to do with it. It's a major PITA though.

**Comment by uBlock-user** [comment] 2017-06-18 04:39
I guess I can say I have experienced it too when after moving entire User Data folder and then running chromium, the data got corrupted. The issue is with the Chromium, chrlauncher is fine.

I don't have a solution, but as a workaround if you sync your data to Google's servers you need not to copy/paste anymore. Just login to your google account **via Chromium** which is found as the first setting in Settings menu and let everything sync and once you're done syncing, logout.

**Comment by niutech** [comment] 2017-06-18 09:59
There is a similar Chromium issue where it's said that user profiles
sadly cannot be moved:
https://bugs.chromium.org/p/chromium/issues/detail?id=419855#c10

Is there a workaround other than syncing to Google servers? E.g.
commenting out some Chromium source code?

**Comment by narcolepticinsomniac** [comment] 2017-06-18 19:13
That bug report was referring to Chrome. They implemented the locking of profile settings to the computer they're installed on a long time ago. They were talking about ~v40 there. This arbitrary restriction was strictly a Google thing though. Chromium remained truly portable until recently, in the last few months. 

I agree that syncing to Google servers sucks. First of all, most of us use Chromium (at least in part) because we want to give Google as little info as possible. Secondly, it's been a long time since I used Google sync, but IIRC, it's not even close to the same thing. Yes it syncs installed extensions, but not local extension settings or extension DB's. All the little tweaks you make are what makes copying/pasting entire portable installs so convenient. It'll be a damn shame if the Chromium team fucked this up just so Chromium would suck in the same way as Chrome.

**Comment by uBlock-user** [comment] 2017-06-18 19:45
https://bugs.chromium.org/p/chromium/issues/detail?id=419855#c54

> Moving User Data directories isn't supported

It's by-design, so they're not gonna fix it.

> commenting out some Chromium source code?

and who's going to do that ? You do realise how huge Chromium source code is ? Good luck with that.


> but not local extension settings or extension DB's. 

Yes it does. Everything you make change to, is synced. I have been doing this for months on various machines and I get the exact same profile with all settings intact. If you dislike sending your info to Google then that's a whole another thing, but this is the best we have at the moment. Well you're already sending a bucket of info and more if you're a Windows user, so in that comparision it's hardly a pee sprinkle in the water 😆

**Comment by narcolepticinsomniac** [comment] 2017-06-18 21:06
> You do realise that Chrome is clone of Chromium with some added shit by Google ? So yes, it applies to Chromium and then Chrome.

For the most part, yes, but what you're failing to realize is that profiles being locked to specific computers was strictly Chrome. That bug thread goes back years, and the last comment was in February. Copying and pasting entire profiles worked in Chromium that entire time. Copied/pasted Chromium profiles being corrupted is a new development that just started happening in the last few months.

> Yes it does. Everything you make change to, is synced.

Like I said, it's been years, so maybe it's improved, but I still think this doesn't work with extensions that aren't explicitly set up for it. I believe synced DB's have size limitations, which prohibits some extensions from using them. 

> Well you're already sending a bucket load of info to MS and more, if you're a Windows user, so in that comparison it's hardly a pee sprinkle in the water

I dual boot Linux/Win8. You can still set decent privacy options in Win8 and choose which shitty updates are not installed. Eventually I'll lose Windows altogether, because I'll never use 10. I never sign in to any Google services in Chromium, and I have all known analytics servers blocked at the OS level. The tinfoil hat can only be made so thick, but I cannot subscribe to the idea that "They already have enough of your personal info, so you might as well give them an account to tie to your IP". That type of thinking is exactly why they do this type of shit, because they can get away with it. That's all well and good for their proprietary version, but shoehorning it into the "open source" version is disturbing. 

Btw, I have no delusions of grandeur that my data is so top secret in particular, but I also can't subscribe to the "If you have nothing to hide, why do you care if they spy on you?" philosophy. Nothing top-secret going on in my backyard either, but if somebody climbed up on the fence and recorded my barbecue, I wouldn't be okay with that either.

**Comment by uBlock-user** [comment] 2017-06-19 12:02
Chromium base keeps changing everyday, if it worked before, doesn't necessarily mean it will work now.

> The tinfoil hat can only be made so thick, but I cannot subscribe to the idea that "They already have enough of your personal info, so you might as well give them an account to tie to your IP". That type of thinking is exactly why they do this type of shit, because they can get away with it

It's not an idea. As you said yourself "The tinfoil hat can only be made so thick". You can't stop everything. You can patch as many manual settings as you can and then there's still some that will be sent and you won't be able to stop that unless you compile your own Chromium from scratch or use ungoogled-Chromium which is broken as fuck!

Yes they're already doing it and getting away with it because it's their product and their terms and conditions and we're the ones using their products. So what are you going to do ? You don't have an exact solution here. Either use the workaround, or try a different browser. But here comes another problem. Firefox does the same. They also collect data and you can block some of it but there's no guarantee that you're blocking everything. Some of it is still being sent. 

I'm not saying you shouldn't care but at some point you have to just let go, you can't control every aspect of the browser. Chromium is open-sourced, but what goes into the project is not open - source and not anyone can just add anything they want or remove anything they dislike, it is being decided by the committee, so not everything is green on the other side, just because it's open-source. Anyways lets stick to the topic and not go into the discussion of data-mining by Google and other corps.

**Comment by uBlock-user** [comment] 2017-06-19 12:48
Still you shouldn't face this issue if you're using chrlauncher's folders and transferring. I faced it when I used archive builds provided by Google'servers where it stores the User Data folder in C drive.

**Closed** 2017-08-31 11:39 UTC
