### ISSUE TITLE
[Question] Regarding BeforeScriptExecute/AfterScriptExecute

### ISSUE THREAD

**Issue by uBlock-user** [henrypp/chromium#11] opened 2016-11-19 12:16 UTC
@chrme Would you be willing to add support for BeforeScriptExecute/AfterScriptExecute to Chromium builds ? Chromium Dev team has officially denied the request regarding this issue[1] for their political reasons or for their own personal agendas, so I am wondering.

It will most certainly be of immense help to users of Chromium extensions which block web content like uBlock Origin(6 million+ and counting) and other content blockers like Adblock, adguard etc, where they can use inline script tag filtering mechanism to search for a specific javascript function within a javascript and block it before it executes. 

It's also officially a part of W3C recommendation standards for HTML5[2] and Firefox team already implemented it.

[1] -  https://bugs.chromium.org/p/chromium/issues/detail?id=168175

[2] - https://www.w3.org/TR/html5/scripting-1.html#scripting-1

**Comment by chrme** [comment] 2016-11-20 10:04
@uBlock-user well, if you provide me with a patch that enable this feature (for dev or stable) and it will not be too complex, then i think i can try.

**Comment by uBlock-user** [comment] 2016-11-20 11:07
@chrme Sorry, I'm not a coder or a developer so I don't know anything about that patch, but can this help ?

`document.addEventListener('beforeload', function(event) {
    var target = event.target;
    if (target.nodeName.toUpperCase() !== 'SCRIPT') return;
    var dispatchEvent = function(name, bubbles, cancelable) {
        var evt = new CustomEvent(name, {
            bubbles: bubbles,
            cancelable: cancelable
        });
        target.dispatchEvent(evt);
        if (evt.defaultPrevented) {
            event.preventDefault();
        }
    };
    var onload = function() {
        cleanup();
        dispatchEvent('afterscriptexecute', true, false);
    };
    var cleanup = function() {
        target.removeEventListener('load', onload, true);
        target.removeEventListener('error', cleanup, true);
    }
    target.addEventListener('error', cleanup, true);
    target.addEventListener('load', onload, true);

    dispatchEvent('beforescriptexecute', true, true);
}, true);`

I took that code from here - http://stackoverflow.com/questions/18323757/how-do-you-detect-that-a-script-was-loaded-and-executed-in-a-chrome-extension

Read the first answer with the 6 votes.

**Comment by chrme** [comment] 2016-11-20 19:30
@uBlock-user yeah i see that, but it didn't help (i'm also not a coder :smiley:). The problem is that it has been completely removed from the sources (all traces) and i can't even find old files... plus for this years the sources changes a lot.

**Comment by uBlock-user** [comment] 2016-11-20 21:50
@chrme Well so I guess there's no other option left then ?

**Comment by chrme** [comment] 2016-11-21 08:59
@uBlock-user i guess, but maybe there is an alternative in extension api, i don't know...

**Comment by uBlock-user** [comment] 2016-11-21 09:13
@chrme so should I just just close this issue then ? or is there anything you can do ?

**Comment by chrme** [comment] 2016-11-22 12:49
@uBlock-user sure you can close this.

**Closed** 2016-11-22 13:08 UTC
